spring:
  profiles.active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: JavaCodeSetDatabaseSuperAdmin
    password: JavaCodeSetSecretPassword
  liquibase:
    change-log: db/changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  token:
    prefix: Bearer_
    secret: JavaCodeSetSecret
    expired: 3600000

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://database:5432/JavaCodeSetDatabase?serverTimezone=UTC
server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaCodeSetDatabase?serverTimezone=UTC
server:
  port: 8075